# Generated by Django 4.1.1 on 2023-01-21 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Vardas')),
                ('lastname', models.CharField(max_length=15, verbose_name='Pavarde')),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Adresas')),
                ('city', models.CharField(max_length=20, verbose_name='Miestas')),
                ('country', models.CharField(max_length=30, verbose_name='Salis')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('v', 'VIP'), ('g', 'GOLD'), ('p', 'PREMIUM'), ('s', 'STANDART')], default='s', help_text='Viesbucio tipas', max_length=1)),
                ('stars', models.CharField(blank=True, choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='s', help_text='Zvaigzduciu kiekis', max_length=1)),
                ('description', models.TextField(default='Super hotel', max_length=2000, verbose_name='Aprasymas')),
                ('availability', models.IntegerField(verbose_name='Kiekis')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Uzsakymo_data')),
                ('r_date', models.DateTimeField(blank=True, null=True, verbose_name='Registracijos_data')),
                ('i_date', models.DateTimeField(blank=True, null=True, verbose_name='Isvykimo_data')),
                ('status', models.CharField(blank=True, choices=[('u', 'Uzsakyta'), ('r', 'Ruosiama'), ('p', 'Paruosta')], default='u', help_text='Status', max_length=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.client')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(max_length=10, verbose_name='Balance')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.client')),
            ],
        ),
    ]
