# Generated by Django 4.1.1 on 2023-01-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Adresas', max_length=200, verbose_name='Viesbucio_adresas'),
        ),
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(verbose_name='Kambario_numeris')),
                ('aukstas', models.IntegerField(verbose_name='Aukstas')),
                ('ramybes_valandos', models.CharField(max_length=20, verbose_name='Ramybes_valandos')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.client')),
            ],
        ),
    ]
