# Generated by Django 4.1.1 on 2023-01-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0004_client_user_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
