# Generated by Django 4.1.1 on 2023-01-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0008_remove_client_user_client_password_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.client'),
        ),
    ]
