# Generated by Django 4.1.1 on 2023-01-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0012_balance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
    ]
