# Generated by Django 4.1.1 on 2023-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0016_remove_balance_client_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(null=True, verbose_name='Viesbucio_kaina'),
        ),
    ]
