# Generated by Django 4.1.1 on 2023-01-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0017_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Viesbucio_pavadinimas'),
        ),
    ]
