# Generated by Django 4.1.1 on 2023-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0019_hotel_quantity_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='i_date',
            field=models.DateField(blank=True, null=True, verbose_name='Isvykimo_data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='r_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registracijos_data'),
        ),
    ]
