# Generated by Django 4.1.1 on 2023-01-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0020_alter_order_i_date_alter_order_r_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viesbuciai.order'),
        ),
    ]
