# Generated by Django 4.1.1 on 2023-01-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0021_admindetails_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viesbuciai.admindetails'),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viesbuciai.profile'),
        ),
    ]
