# Generated by Django 4.1.1 on 2023-01-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0022_remove_admindetails_order_order_admin_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_details',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viesbuciai.admindetails'),
        ),
    ]
