# Generated by Django 4.1.1 on 2023-01-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0023_alter_order_admin_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='viesbuciai.admindetails'),
        ),
    ]
