# Generated by Django 4.1.1 on 2023-01-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0025_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
