# Generated by Django 4.1.1 on 2023-01-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0026_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
