# Generated by Django 4.1.1 on 2023-01-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0027_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0, max_length=10, verbose_name='Balance'),
        ),
    ]
