# Generated by Django 4.1.1 on 2023-01-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0028_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photos/'),
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hotel_photos/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='viesbuciai.hotel')),
            ],
        ),
    ]
