# Generated by Django 4.1.1 on 2023-01-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0029_alter_hotel_options_hotel_main_photo_hotelphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='main_photo',
        ),
        migrations.DeleteModel(
            name='HotelPhoto',
        ),
    ]
