# Generated by Django 4.1.1 on 2023-01-30 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0030_remove_hotel_main_photo_delete_hotelphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Zmoniu_kiekis'),
        ),
    ]
