# Generated by Django 4.1.1 on 2023-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viesbuciai', '0031_alter_hotel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gimimo Data'),
        ),
    ]
